### ISSUE TITLE
Expressions in inline styles are shown as errors

### ISSUE THREAD

**Issue by mfn** [johnlindquist/angularjs-plugin#21]
Use of things like:

``` html
<div style="background-color: {{entity.color}}"></div>
```

will be shown as CSS error:
![expression shown as CSS error](http://i.imgur.com/X7O9IvQ.png)

**Comment by denofevil** [comment]
As plugin development has been moved to @JetBrains intellij-plugins repository this issue is now tracked as [WEB-10984](http://youtrack.jetbrains.com/issue/WEB-10984)

**Comment by mfn** [comment]
Thanks. Fixed link: http://youtrack.jetbrains.com/issue/WEB-10984

**Comment by denofevil** [comment]
Thanks, for the fix, I've corrected original message

**Comment by mfn** [comment]
https://youtrack.jetbrains.com/issue/WEB-10984 says it's fixed, I'm not using angular anymore 🤷‍♀️ => closing
