### ISSUE TITLE
Auto import modules

### ISSUE THREAD

**Issue by ffesseler** [johnlindquist/angularjs-plugin#22]
When injecting an object, it would be great to automatically include the module where the dependency is declared.

Another cool option related to modules would be 'Auto import missing modules'

**Comment by denofevil** [comment]
As plugin development has been moved to @JetBrains intellij-plugins repository this issue is now tracked as [WEB-10985](http://youtrack.jetbrains.com/issue/WEB-10985)

**Comment by ffesseler** [comment]
Ok thanks.

Does it mean the plugin won't be open sourced any more ?

**Comment by denofevil** [comment]
It will stay open source, source is now available [here](https://github.com/JetBrains/intellij-plugins/tree/master/AngularJS)

**Comment by ffesseler** [comment]
ok thx :)
