### ISSUE TITLE
-data prefix

### ISSUE THREAD

**Issue by cubeweb** [johnlindquist/angularjs-plugin#27]
Great plugin,

This is not an issue, its a small request. Do you think you could add an option for ng- attributes to have data- prefix? Like data-ng-model, just for html5 validation.

Thanks

**Comment by denofevil** [comment]
Because AngularJS plugin is moved to JetBrains/intellij-plugins, this issue is now tracked as [WEB-10979](http://youtrack.jetbrains.com/issue/WEB-10979)
