### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jmaynier** [johnlindquist/angularjs-plugin#3]
When loading the zip file in IntelliJ 11.1.3, it says that 'Required plugin "JavaScript " is not enabled'.
There is no official JavaScript plugin in the repos. 
Where do I find it ?

**Comment by johnlindquist** [comment]
JavaScript should be one of the bundled plugins (not in the repo).

**Comment by jmaynier** [comment]
Ok in fact in was because I'm using IntelliJ Community Edition. The JavaScript plugin is only in the Ultimate edition and in all editions of PHP/WebStrom.
So for the moment I tried the plugin with WebStorm.
