### ISSUE TITLE
After installing version 0.1.8 keyboard input ceased to function

### ISSUE THREAD

**Issue by ghost** [johnlindquist/angularjs-plugin#32]
This happens in Windows and Linux.
After deactivating plugin keyboard works proper, reactivating AngularJS, only backspace (deletes characters) and ctrl/z (undo the delete) works, as well as ctrl/c and ctrl/v.
I can't possibly be the only one who has this problem. It took me a day and a half to find out why my keyboard wouldn't work any more. Only after read an article from 2003 where a guy had similar problems and found out that it was related to a plugin he installed, I had a wow.

Anyway thanks for the great job with the plugin and I am sure I will be able to use it soon.

Cheers
Guenther

**Comment by johnlindquist** [comment]
Are you installing from the File->Settings->Plugins->Browse menus?
- Sent from my phone

**Comment by ghost** [comment]
Exactly so:
I uncheck AngularJS, apply, restart, keyboard works.
I check AngularJS, apply, restart, keyboard stops working.

I wonder how I possibly could be the only one with this problem?
I tried loads of different things before, like switching from OpenJDK to 
OracleJDK.
Nothing helped.

Thanks for the quick response.
Greetings from London
Guenther

**Comment by ghost** [comment]
Hello,

Problem solved!
I contacted JetBrains and they came up with the following:
*Seems that kotlin-runtime.jar is missing from 
~.WebStorm6\config\plugins\angularjs-plugin\lib; please make sure to 
remove the angularjs plugin and reinstall it from the repository. *

They were right:
There was no kotlin-runtime.jar; somthing must have gone wrong while 
downloading the plugin.
Removing the angularjs-plugin folder enforced a re-download of the 
plugin inclueding the missing .jar.
Everything works fine.

Thank you for your time and effort and for the great plugin!
Best regards
Guenther

On 15/09/2013 04:11, johnlindquist wrote:

> Are you installing from the File->Settings->Plugins->Browse menus?
> - Sent from my phone
>   On Sep 14, 2013 8:27 PM, "Guenther" notifications@github.com wrote:
>   > This happens in Windows and Linux.
>   > After deactivating plugin keyboard works proper, reactivating 
>   AngularJS,
>   > only backspace (deletes characters) and ctrl/z (undo the delete) 
>   works, as
>   > well as ctrl/c and ctrl/v.
>   > I can't possibly be the only one who has this problem. It took me a day
>   > and a half to find out why my keyboard wouldn't work any more. Only 
>   after
>   > read an article from 2003 where a guy had similar problems and found 
>   out
>   > that it was related to a plugin he installed, I had a wow.
>   >
>   > Anyway thanks for the great job with the plugin and I am sure I will be
>   > able to use it soon.
>   >
>   > Cheers
>   > Guenther
>   >
>   > —
>   > Reply to this email directly or view it on 
>   GitHubhttps://github.com/johnlindquist/angularjs-plugin/issues/32
>   > .
>   >
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/johnlindquist/angularjs-plugin/issues/32#issuecomment-24463537.

## 

---

Guenther Zoppelt    phone   +44 (0) 1442 213617
18 Longdean Park    fax     +44 (0) 1442 216839
Hemel Hempstead     mobile  +44 (0) 790 8144 800
HP3 8BZ     work    +49 (0) 7641 4602 468
U.K.    email   gzoppelt@gmail.com
