### ISSUE TITLE
{{   }}  autocomplete ...  should be without spaces!

### ISSUE THREAD

**Issue by klwemu** [johnlindquist/angularjs-plugin#33]
I dont want the useless blankes.

a) can i disable this feature in phpStorm??
b) or please change in "AngularBracesInterpolationTypedHandler"  the line ...
      interpolation = "{  }"

The blankes are useless and more difficult to read in complex situations ...

**Comment by johnlindquist** [comment]
This is now a setting under Preferences->AngularJS
