### ISSUE TITLE
Missing support for the ng-disabled attribute

### ISSUE THREAD

**Issue by pkozlowski-opensource** [johnlindquist/angularjs-plugin#4]
@johnlindquist I'm very much missing support for the ng-disabled from the latest release of the plugin, could this be added? There is also https://github.com/johnlindquist/angularjs-plugin/pull/2 waiting :-)

**Comment by johnlindquist** [comment]
Done.

**Comment by pkozlowski-opensource** [comment]
Wow! This was fast :-)

**Comment by johnlindquist** [comment]
After some intense brainstorming of how I could ever possibly accomplish
your request, the answer came to me in a vision of amber light. My fingers
began typing. Faster and faster and faster. The keystrokes landing like
hailstones in a thunderstorm.

Ok, I'm done. Yeah, adding two strings to a file and clicking "commit +
push" is hard :)
