### ISSUE TITLE
No PyCharm support?

### ISSUE THREAD

**Issue by adamJLev** [johnlindquist/angularjs-plugin#50]
This plugin is not showing up in the repository for me.  
Seems strange since the other intelliJ products are supported, so just making sure.
I'm using PyCharm 3.1.1

Thanks!

**Comment by vbabiy** [comment]
@johnlindquist said this on twitter:

> @filippovdmitry @vitaly_babiy @pycharm the plugin requires 134, so any build >134 should be fine :)
> https://twitter.com/johnlindquist/status/448825633926168576

The pycharm team responded with: 

> filippovdmitry: @vitaly_babiy @pycharm @johnlindquist 135 you mean? The PyCharm 3.4 EAP, which is going to be published in 1-2 weeks is based on b135
> https://twitter.com/filippovdmitry/status/448768841737568256

**Comment by adamJLev** [comment]
Awesome, thanks for digging in!
