### ISSUE TITLE
Plugin Settings not shown in Preferences in Webstorm 8.0

### ISSUE THREAD

**Issue by 4kochi** [johnlindquist/angularjs-plugin#51]
I have updated my Webstorm 7 to Webstorm 8 (135.547). Now under Preferences there is no more entry AngularsJS. Reinstalling the plugin didn't help.

**Comment by denofevil** [comment]
Closing interpolations with }} is now handled by global setting (Editor | Smart keys | Insert pair bracket). Whitespace insertion is Editor | Smart keys | AngularJS

**Comment by 4kochi** [comment]
Thank, now i found it :+1:

**Comment by mdoelker** [comment]
It cannot be found using the search field though. The only result is the Plugins page. When I have the Smart Keys page open, I can see the AngularJS section getting correctly outlined for the brief moment before the Plugins page is auto-selected from the results, but the Smart Keys page is not listed.
