### ISSUE TITLE
Angular directives with ':' not allowed.

### ISSUE THREAD

**Issue by sephie** [johnlindquist/angularjs-plugin#7]
Call me weird, but I somehow decided to use directives like so:

`<div ng:view></div>`

The plugin does not handle the colon well it seems.

Thanks for the plugin though!

**Comment by denofevil** [comment]
Because plugin development has moved to JetBrains/intellij-plugins, this issue is now tracked as [WEB-10982](http://youtrack.jetbrains.com/issue/WEB-10982)
